### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by msgoussi** [tonyfischetti/myR#1]
If i want to run update.packages() in rprofile using rstudio, it give me error.
Any advice on that.

**Comment by tonyfischetti** [comment]
Can you copy and paste the error?

**Comment by msgoussi** [comment]
![error 1](https://user-images.githubusercontent.com/18138496/31754151-5a16d82a-b49e-11e7-97cd-939cf946530f.JPG)
![error 2](https://user-images.githubusercontent.com/18138496/31754152-5a37e330-b49e-11e7-88ca-5ce528522c2b.JPG)

**Comment by tonyfischetti** [comment]
And this error doesn't occur when you remove the `update.packages()` line from `.rprofile`?

**Comment by msgoussi** [comment]
when i remove the update.packages() line from .rprofile, there is no error.
Yes.
